Task b cc
navid-hossain/AlternateBitProtocolSimulator pull request #4
Opened 2019-08-05 07:38 UTC by tarimislam

cpp files are modified according to code convention

2019-08-06 07:43 UTC, hamza-sadruddin requested changes
In each file according to rule 13. have header guards professor has given 2 guards at end and beginning. The same follows for file subnetCadmium.hpp
example:
```
#ifndef MY_HEADER
#define MY_HEADER
... #endif // __ MY_HEADER__
```

https://github.com/navid-hossain/AlternateBitProtocolSimulator/blob/2414dec50046af0773523620b7cacc58d2321be9/include/atomics/receiverCadmium.hpp#L7-L8

2019-08-06 07:52 UTC, hamza-sadruddin requested changes

2019-08-06 07:52 UTC, hamza-sadruddin commented on include/atomics/subnetCadmium.hpp
> +    struct subnet_defs{
Please have it indented, to the first column.

2019-08-06 07:52 UTC, hamza-sadruddin commented on include/atomics/subnetCadmium.hpp
>                  out.value = state.packet;
Please indent the inside block of if statement to 4 spaces.

2019-08-06 08:00 UTC, hamza-sadruddin requested changes
Please use lower case letters for naming files according to the convention. eg. receiverCadmium.hpp, becomes receiver_cadmium.hpp.

2019-08-07 04:25 UTC, khanyousefzai commented on test/src/receiver/main.cpp
>  public:
check indentation

2019-08-07 04:30 UTC, khanyousefzai requested changes

2019-08-07 04:30 UTC, khanyousefzai commented on test/src/receiver/main.cpp
> +    ApplicationGen() = default;
Check indentation

2019-08-07 04:30 UTC, khanyousefzai commented on test/src/receiver/main.cpp
> +    auto start = hclock::now(); //to measure simulation execution time
Check indentation

2019-08-07 04:30 UTC, khanyousefzai commented on test/src/receiver/main.cpp
> -            return out_data;
Check indentation

2019-08-07 04:30 UTC, khanyousefzai commented on test/src/receiver/main.cpp
> -  cadmium::dynamic::translate::make_EOC<Receiver_defs::out,outp>("receiver1")
Check indentation

2019-08-07 04:30 UTC, khanyousefzai commented on test/src/receiver/main.cpp
> -  cadmium::dynamic::translate::make_IC<iestream_input_defs<Message_t>::out,Receiver_defs::in>("generator","receiver1")
Check indentation

2019-08-07 04:30 UTC, khanyousefzai commented on test/src/sender/main.cpp
> +       "TOP",
Check indentation

2019-08-10 06:13 UTC, tarimislam commented on test/src/receiver/main.cpp
>  public:
Changes have been done

2019-08-10 06:13 UTC, tarimislam commented on test/src/receiver/main.cpp
> +    ApplicationGen() = default;
Changes have been done

2019-08-10 06:19 UTC, tarimislam commented on test/src/receiver/main.cpp
> -  cadmium::dynamic::translate::make_IC<iestream_input_defs<Message_t>::out,Receiver_defs::in>("generator","receiver1")
Changes have been done

2019-08-10 06:19 UTC, tarimislam commented on test/src/sender/main.cpp
> +       "TOP",
Changes have been done

2019-08-10 06:23 UTC, tarimislam commented on test/src/receiver/main.cpp
> -  cadmium::dynamic::translate::make_EOC<Receiver_defs::out,outp>("receiver1")
Changes have been done

2019-08-13 01:45 UTC, hamza-sadruddin approved these changes
Looks good to me.

2019-08-14 15:29 UTC, khanyousefzai approved these changes

2019-08-14 15:30 UTC, khanyousefzai commented
It looks Ok.

2019-08-19 05:03 UTC, merged